config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users

  get "/panels/:id/available_dates/", to: "panels#available", as: "available"
  patch "/campaigns/:id/", to: "campaign#upload"

  patch "/campaigns/:id/paid", to: "campaigns#paid", as: "payment"

  resource :users, only: [:show]

  resources :campaigns, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :companies, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :panels, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/panel.rb
class Panel < ApplicationRecord
  paginates_per 24
  belongs_to :panel_type
  belongs_to :station
  has_many :orders

  monetize :price_cents

  validates :price_cents, presence: true

  include PgSearch
  pg_search_scope :station_search,
    associated_against: {
      station: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }


  def calculate_dates
    orders.includes(:campaign).map do |order|
      if order.campaign.paid
        start_date = order.date.to_date
        {
          from: start_date.strftime("%d/%m/%Y"),
          to: (start_date + order.duration).strftime("%d/%m/%Y")
        }
      end
    end
  end
end

app/models/panel_type.rb
class PanelType < ApplicationRecord
  has_many :panels

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :total_area, presence: true
  validates :visible_area, presence: true
  validates :security_area, presence: true
  validates :impression, presence: true

  monetize :price_cents
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :set_panel, only: [:show, :available, :calculate_dates]
  skip_before_action :store_user_location!, only: :show
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @panels =
      if params[:station].present?
        if params[:station].length > 1
          panels =
            params[:station].flat_map do |station|
              Panel.includes(:panel_type, :station).station_search(station)
            end
           Kaminari.paginate_array(panels).page(params[:page]).per(24)
        else
          Panel.includes(:panel_type, :station).page(params[:page]).per(24).station_search(params[:station])
        end
      else
        Panel.includes(:panel_type, :station, station: :lines).page(params[:page])
      end
  end

  def show
    @back = stored_location_for(:user)
    if user_signed_in?
      @dates = @panel.calculate_dates
      @order = @panel.orders.build
      @companies = Company.where(status: :active, user: current_user)
      @campaign = Campaign.new
      @company = Company.new
      @campaigns = []
      @companies.includes(:campaigns).each do |company|
        company.campaigns.each do |campaign|
          @campaigns << campaign unless campaign.archived? || campaign.paid
        end
      end
    end
    if @panel.price == 0
      @price = @panel.panel_type.price
      @price_cents = @panel.panel_type.price_cents
    else
      @price = @panel.price
      @price_cents = @panel.price_cents
    end
  end

  def available
    # /panels/1/available_dates || available_path(panel)
    dates = @panel.calculate_dates
    render json: dates
  end

  private

  def set_panel
    @panel = Panel.find(params[:id])
  end
end

app/views/panels/_choose_campaign_parameters.html.erb
<%= simple_form_for [@panel, @order] do |f| %>

  <div class="choose-campaign">
    <p class="label-title">Selecione a campanha que você está montando:</p>
    <%= f.association :campaign, collection: @campaigns.select {|campaign| campaign.active? }, prompt: 'Escolhe uma campanha', label: false, selected: @campaigns.select {|campaign| campaign.active? }.last %>
    <p class="link-cadastrar-empresa">Clique <a href="#" data-toggle="modal" data-target=".campaign-modal">aqui </a> para cadastrar uma nova campanha</p>
  </div>

  <div class="choose-duration">
    <p class="label-title">Escolha a duração da veículação da campanha:</p>
    <div class="form-group select required order_campaign">
     <%= f.select :duration, [['1 mês', 28], ['2 meses', 56], ['3 meses', 84], ['4 meses', 112], ['5 meses', 140], ['5 meses', 168], ['6 meses', 196], ['7 meses', 224], ['8 meses', 252], ['9 meses', 280], ['10 meses', 308], ['11 meses', 336], ['12 meses', 364]], { required: true }, { class: "form-control select required"} %>
    </div>
  </div>

  <div class="choose-dates">
    <p class="label-title">Escolha a data de início da veículação da sua campanha:</p>
    <%= f.input :date, required: false, label: false, input_html: { class: "panel-date" }, placeholder: 'Data de início da campanha' %>
    </div>
  </div>

  <div class="total-price text-right">
    <p id="total_price" data-price="<%= @price_cents %>"><%= humanized_money_with_symbol(@price_cents/100) %></p>
  </div>

  <%= f.submit 'Adicionar painel a campanha', class: 'btn btn-primary btn-block', id: 'add-panel', disabled: true %>

<% end %>

app/views/panels/_print_info.html.erb
<h6>Conheça os requerimentos para a criação da arte:</h6>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Area total:</th>
      <th>Area visivel:</th>
      <th>Area de segurança:</th>
      <th>Impressão:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @panel.panel_type.total_area %></td>
      <td><%= @panel.panel_type.visible_area %></td>
      <td><%= @panel.panel_type.security_area %></td>
      <td><%= @panel.panel_type.impression %></td>
    </tr>
  </tbody>
</table>
<div class="obs-footer">
  <p>NB: O cliente deve fazer o upload da arte nesse site no maximo 15 dias antes do inicio da veiculação. A JCDecaux se responsabiliza pela aprovação do visual e a impressão do cartaz.</p>
</div>

app/views/panels/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" align="center">
      <%= paginate @panels %>
    </div>

    <% @panels.each do |panel| %>
      <div class="col-xs-12 col-sm-4 col-md-4 cards-margin " >
        <%= link_to panel_path(panel), class: "card-link" do %>
          <div class="card-wrap">
              <div class="img-wrap" style="background-image: url(<%= panel.panel_type.picture %>)">
                <div class="metro-icon">
                  <%= cl_image_tag("Logo/icon_metro_card.png", height: 60) %>

                </div>


              </div>
          <% end %>
              <%= link_to panel_path(panel), class: "card-link" do %>

              <div class="card-footer-wrap">

                <div class="card-info">

                  <div class="row">

                    <div class="col-md-12">
                  <div class="col-md-6">
                    <h6><strong><%= panel.panel_type.name %></strong></h6>
                    <small>A partir de</small>
                    <strong><% if panel.price == 0 %>
                      <%= humanized_money_with_symbol(panel.panel_type.price) %>
                    <% else %>
                      <%= humanized_money_with_symbol(panel.price) %>
                    <% end %></strong><small>/ painel</small>
                  </div>

                   <div class="col-md-6">
                    <button type="button" class="btn btn-detalhes">Saiba mais</button>
                  </div>

                  </div>


                </div>
                <div class="row">
                 <div class="col-md-11 card-info-border centered">

                  </div>
                  </div>

                  <div class="row">
                 <div class="col-md-11 centered info-card">
                  <p><i class="fa fa-train" aria-hidden="true"></i> <%= panel.station.name %></br><i class="fa fa-road" aria-hidden="true"></i>
                      <% panel.station.lines.each do |line| %>
                <%= line.name %> /
              <% end %></br>

            <i class="fa fa-file-image-o" aria-hidden="true"></i> <%= panel.panel_type.total_area %></br>
            </p>

                  </div>
                  </div>

                </div>


              </div>
              <% end %>
          </div>
      </div>
    <% end %>
    <div class="col-md-12" align="center">
      <%= paginate @panels %>
    </div>
  </div>
</div>

app/views/panels/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-md-12">
          <%= link_to @back, class: "back-button" do%>
            <p><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Voltar</p>
          <% end %>
        </div>
      </div>

      <div class="row">

        <div class="information-wrap">
          <div class="col-xs-7">
            <% @panel.station.lines.each do |line| %>
              <p><%= cl_image_tag("Logo/logo-metrô.png", height: 20) %>
              <%= line.name %></p>
            <% end %>
            <p><strong>Estação: </strong><%= @panel.station.name %></p>
          </div>

          <div class="col-xs-5">
            <h3><%= @panel.panel_type.name %></h3>
          </div>
        </div>
      </div>


      <div class="row">

        <div class="col-md-7">
          <div class="panel-picture-wrap">
            <% if @panel.picture %>
              <%= cl_image_tag(@panel.picture, height:'100%', width: '100%') %>
            <% else %>
             <%= cl_image_tag(@panel.panel_type.picture, height:'100%', width: '100%') %>
            <% end %>
          </div>
        </div>

        <div class="col-md-5">
          <% if user_signed_in? %>
            <div class="panel-buy-wrap">
              <ul class="hidden">
                <% @dates.each do |date| %>
                  <li class="dates" data-datefrom="<%= date[:from] %>" data-dateto="<%= date[:to] %>">
                  </li>
                <% end %>
              </ul>
              <% if @companies.present? %>
                <% if @campaigns.empty? %>
                  <div class="text-left">
                    <h5>Você não possui nenhuma campanha ativa</h5>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".campaign-modal">Montar nova campanha</button>
                  </div>
                <% else %>
                  <%= render 'panels/choose_campaign_parameters' %>
                <% end %>
              <% else %>
                <div class="text-left">
                  <h4>
                    Registre uma empresa antes de adicionar painéis ao seu carrinho:
                  </h4>
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".company-modal">Registrar uma empresa</button>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="panel-buy-wrap">
              <div class="text-left">
                <h5>Selecione painéis e monte sua campanha</h5>
                <%= link_to "Comece já !", new_user_session_path, class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>


        <div class="row">
          <div class="col-xs-12 col-md-7 printing-data">
            <%= render 'panels/print_info' %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <div class="modal fade company-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content background">
        <%= render template: "companies/new" %>
      </div>
    </div>
  </div>
  <div class="modal fade campaign-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content background">
        <%= render template: 'campaigns/new' %>
      </div>
    </div>
  </div>
<% end %>