config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users

  get "/panels/:id/available_dates/", to: "panels#available", as: "available"
  patch "/campaigns/:id/", to: "campaign#upload"

  patch "/campaigns/:id/paid", to: "campaigns#paid", as: "payment"

  resource :users, only: [:show]

  resources :campaigns, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :companies, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :panels, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="flex">
        <div class="col-sm-12 col-md-2">
          <div class="footer-logo">
            <%= link_to "http://www.jcdecaux.com.br/" do%>
              <% cl_image_tag("Logo/JCDecaux_logo.svg") %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-12 col-md-7">
          <div class="footer-copyright">
            <p class="text-center"><i class="fa fa-copyright"></i>2018 <a href="http://www.jcdecaux.com">JCDecaux SA</a> - Todos os direitos reservados</p>
          </div>
        </div>
        <div class="col-sm-12 col-md-3">
          <div class="footer-links">
            <a href="https://www.youtube.com/playlist?list=PLVZXI6E6mVBXfgV75JvRbWogCJ_RGxVKh"><i class="fa fa-youtube"></i></a>
            <a href="https://www.instagram.com/jcdecauxglobal/"><i class="fa fa-instagram"></i></a>
            <a href="https://www.facebook.com/JCDecaux/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/jcdecauxglobal"><i class="fa fa-twitter"></i></a>
            <a href="https://www.linkedin.com/company/jcdecaux/?originalSubdomain=br"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_page?(root_path) %>
  <div class="navbar-wagon navbar-fixed-top">
    <% else %>
  <div class="navbar-wagon-grey">
<% end %>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag("logo.png")%>
  <% end %>
  <% unless current_page?(root_path) %>

    <%= render 'shared/search-form' %>


  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <div class="navbar-wagon-item">
        <div class="navbar-wagon-button">
          <div class="my-account">
            <%= link_to "Minha conta", users_path %>
          </div>
        </div>
        <div class="navbar-wagon-button">
          <div class="log-out navbar-wagon-link">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Sair") %>
            <% end %>
          </div>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <div class="navbar-wagon-button">
        <div class="link-entrar-wrap">
          <%= link_to t(".sign_in", default: "Entrar"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <%= link_to t(".sign_in", default: "Cadastrar-se"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>

      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Minha conta", users_path %></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %><%= t(".sign_out", default: "Sair") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to t(".sign_in", default: "Entrar"), new_user_session_path %></li>
            <li><%= link_to t(".sign_in", default: "Cadastrar-se"), new_user_registration_path %>
            </li>
          </ul>
        </div>
      </div>

    <% end %>


</div>

<% unless current_page?(root_path) %>

    <%= render 'shared/search-form-mobile' %>



  <% end %>

app/views/shared/_search-form-mobile.html.erb
<form action="<%= panels_path %>" id="search-form-mobile">
  <div class="search-section">
    <div class="input-group search-wrapper">
      <%= image_tag "metro_icon.png", width: 30 %>
      <%= select_tag 'station[]', option_groups_from_collection_for_select(Line.all.includes(:stations), :stations, :name, :name, :name, selected: params[:station]), multiple: 'multiple', class: "form-control", id:"select2-mobile" %>
      <%= link_to panels_path do %>
        <button class="btn-primary btn_search btn-easy">Buscar</button>
      <% end %>
    </div>
  </div>
</form>

app/views/shared/_search-form-mobile2.html.erb
<form action="<%= panels_path %>" id="search-form-mobile2">
  <div class="search-section">
    <div class="input-group search-wrapper">
      <%= image_tag "metro_icon.png", width: 30 %>
      <%= select_tag 'station[]', option_groups_from_collection_for_select(Line.all.includes(:stations), :stations, :name, :name, :name, selected: params[:station]), multiple: 'multiple', class: "form-control", id:"select2-mobile2" %>
      <%= link_to panels_path do %>
        <button class="btn-primary btn_search btn-easy">Buscar</button>
      <% end %>
    </div>
  </div>
</form>

app/views/shared/_search-form.html.erb
<form action="<%= panels_path %>" id="search-form-normal">
  <div class="search-section">
    <div class="input-group search-wrapper">
      <%= image_tag "metro_icon.png", width: 30 %>
      <%= select_tag 'station[]', option_groups_from_collection_for_select(Line.all.includes(:stations), :stations, :name, :name, :name, selected: params[:station]), multiple: 'multiple', class: "form-control", id:"select2" %>
      <%= link_to panels_path do %>
        <button class="btn-primary btn_search btn-easy">Buscar</button>
      <% end %>
    </div>
  </div>
</form>