config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users

  get "/panels/:id/available_dates/", to: "panels#available", as: "available"
  patch "/campaigns/:id/", to: "campaign#upload"

  patch "/campaigns/:id/paid", to: "campaigns#paid", as: "payment"

  resource :users, only: [:show]

  resources :campaigns, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :companies, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :panels, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  enum status: [ :active, :archived ]
  belongs_to :user
  has_many :campaigns

  validates :cnpj, :name, :street_number, :address1, :address2, :zip_code, :city, :state, presence: true
  validate :check_cnpj
  validates_uniqueness_of :cnpj, conditions: -> { where(status: [:active]) }

  private

  def check_cnpj
    errors.add(:cnpj, "CNPJ invalido, digite apenas numeros") unless CNPJ.valid?(self.cnpj)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_company, only: [:show, :edit, :update, :destroy]

  def show; end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user = current_user
    if @company.save
      sweetalert("  ", "Empresa criada com sucesso", opts = { icon: 'success', button: false, timer: 1400 } )
      redirect_to stored_location_for(:user) || users_path
    else
      sweetalert("  ", "Erro ao criar empresa", opts = { icon: 'error', button: true } )
      redirect_to request.referer
    end
  end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @company.archived!
  end

  private

  def company_params
    params
      .require(:company)
      .permit(
        :name,
        :cnpj,
        :street_number,
        :address1,
        :address2,
        :zip_code,
        :city,
        :state
      )
  end

  def find_company
    @company = Company.find(params[:id])
  end
end

app/views/companies/_form.html.erb
<div class="margin-top-new-company">
  <div class="signin-content col-md-6 col-sm-12 col-xs-12 centered">
    <div class="row">

      <div class="col-md-9 signin-head-title centered" align="center">
        <p>Registra uma empresa na sua conta JCD'easy</p>
      </div>

      <div class="col-md-12 company-form">
        <%= simple_form_for @company do |form| %>
          <div class="form-inputs">
            <%= form.input :name, autofocus: true, placeholder: 'Razão Social', label: false %>
            <%= form.input :cnpj, placeholder: 'CNPJ', label: false %>
            <%= form.input :zip_code, placeholder: 'CEP', label: "Digite seu CEP para autocompletar seu endereço", class: 'company-zipcode' %>
            <%= form.input :address1, placeholder: 'Endereço', label: false %>
            <%= form.input :street_number, placeholder: 'Número', label: false %>
            <%= form.input :address2, placeholder: 'Bairro', label: false %>
            <%= form.input :city, placeholder: 'Cidade', label: false %>
            <%= form.input :state, placeholder: 'Estado', label: false %>
          </div>
          <div class="form-actions signin-btn">
            <%= form.submit "Registrar", class: 'btn btn-primary btn-signin' %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/companies/destroy.js.erb
var company = document.querySelector("[data-company-id='<%= @company.id %>']")
  if (company.parentElement.childElementCount === 1) {
    company.parentElement.parentElement.parentElement.insertAdjacentHTML("afterbegin", "<em><h5>Você ainda não possui empresas registradas</h5></em>")
  }
  company.remove()

app/views/companies/edit.html.erb
<div class="background">
  <div class="container">
    <%= render "companies/form" %>
  </div>
</div>

app/views/companies/new.html.erb
<%= render "companies/form" %>

app/views/companies/show.html.erb
<p><%= @company.name %></p>
<p>CNPJ: <%= @company.cnpj %></p>
<p>Endereço: <%= @company.address1 %> <%= @company.address2 if @company.address2  %> <%= @company.street_number  %>, <%= @company.zip_code  %> <%= @company.city %>, <%= @company.state %></p>
<p><%= link_to "Editar empresa", edit_company_path(@company) %></p>
<p><%= link_to "Deletar empresa", company_path(@company), method: :delete, data: { confirm: "Are you sure?" } %></p>
<% @company.campaigns.each do |campaign| %>
  <p>------------------</p>
  <%= link_to campaign.title, campaign_path(campaign) %>
  <p>Estatus do pagamento :
    <% if campaign.paid %>
      Aprovado
    <% else %>
      Em espera
    <% end %>
  </p>
<% end %>