config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users

  get "/panels/:id/available_dates/", to: "panels#available", as: "available"
  patch "/campaigns/:id/", to: "campaign#upload"

  patch "/campaigns/:id/paid", to: "campaigns#paid", as: "payment"

  resource :users, only: [:show]

  resources :campaigns, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :companies, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :panels, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  enum status: [ :active, :archived ]
  belongs_to :company
  has_many :orders

  validates :title, presence: true
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :find_campaign, only: [:show, :edit, :update, :paid, :destroy]
  before_action :find_companies, only: [:new, :create, :edit, :update]
  skip_before_action :verify_authenticity_token, only: :paid

  def show
    @total = 0
    @total_cents = 0
    @orders = []
    @campaign.orders.includes(:panel).includes(panel: :panel_type).each do |order|
      @orders << {
        id: order.id,
        title: order.panel.panel_type.name,
        unit_price: order.price_cents,
        quantity: 1,
        tangible: true
      }
      @total += order.price
      @total_cents += order.price_cents
    end
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if params[:campaign][:company].present?
      @campaign.company = Company.find(params[:campaign][:company])
      if @campaign.save
        sweetalert(' ', "Campanha criada com sucesso", opts = { icon: 'success', button: false, timer: 1400 } )
        redirect_to request.referer
      else
        sweetalert("Você precisa nomear sua campanha", "Erro ao criar campanha", opts = { icon: 'error', button: true } )
        redirect_to stored_location_for(:user)
      end
    else
      sweetalert("Você deve associar a campanha à uma empresa", "Erro ao criar campanha", opts = { icon: 'error', button: true } )
      redirect_to stored_location_for(:user)
    end
  end


  def edit; end

  def update
    if @campaign.update(campaign_params)
      redirect_to campaign_path(@campaign)
    else
      render :edit
    end
  end

  def paid
    @campaign.update_attributes(paid: true)
  end

  def destroy
    @campaign.archived!
  end

  private

  def find_campaign
    @campaign = Campaign.find(params[:id])
  end

  def find_companies
    @companies = Company.where(status: :active, user: current_user)
  end

  def campaign_params
    params.require(:campaign).permit(:title, :company_id, :paid)
  end
end

app/views/campaigns/_form.html.erb
<div class="margin-top-new-campaign">
  <div class="signin-content col-md-6 col-sm-12 col-xs-12 centered">
    <div class="row">

      <div class="col-md-9 signin-head-title centered" align="center">
        <p>Começe a montar sua campanha na JCD'easy</p>
      </div>

      <div class="col-md-12 campaign-form">
        <%= simple_form_for [@campaign] do |f| %>
          <div class="form-inputs">
            <%= f.input :title, autofocus: true, placeholder: '"Campanha promoção dia dos namorados"', label: "Dê um título à sua nova campanha" %>
          </div>
            <% if @companies.present? %>
              <div class="form-group select required">
                <%= f.select :company, @companies.map { |company| [company.name, company.id]}, { required: true, prompt: "Selecione a empresa a ser faturada após o pagamento" }, { class: "field-select-company form-control select required" } %>
              </div>
              <p class="link-cadastrar-empresa">Clique <%= link_to "aqui", new_company_path %> para cadastrar uma nova empresa</p>
            <% else %>
              <p>Você ainda não cadastrou nenhuma empresa no seu perfil</p>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".company-modal">Criar empresa</button>
            <% end %>
          <div class="form-actions signin-btn">
            <%= f.submit "Começar a montar minha campanha", class: 'btn btn-primary btn-signin', disabled: true, id: 'add-campaign'   %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade company-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content background">
      <%= render template: "companies/new" %>
    </div>
  </div>
</div>

app/views/campaigns/_not_paid.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="title-wrap">
      <h4><%= @campaign.title %> - <%= @campaign.company.name %></h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="panels-wrap">
        <ul class="list-unstyled">
        <% @campaign.orders.each do |order| %>
          <li>
            <div class="row">
              <div class="col-md-3 pic-wrap">
                <%= cl_image_tag(order.panel.panel_type.picture, class:"pic") %>
              </p>
              </div>
              <div class="col-md-9">
                <div class="row">
                  <div class="col-md-12">
                <div class="col-info">
                  <p><strong><%= order.panel.panel_type.name %></strong></p>
                  <p><%= humanized_money_with_symbol(order.price) %><%= link_to order_path(order), method: :delete, data: { confirm_swal: ''} do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
</p>
            </div>
            <div class="col-md-12">
                  <div class="order-infos">
                    <p><i class="fa fa-train" aria-hidden="true"></i> <%= order.panel.station.name %></p>
                <p><i class="fa fa-calendar-o" aria-hidden="true"></i> <%= order.date.to_date.strftime("%d/%m/%Y") %></p>
                <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= order.duration %> dias</p>
                <p><i class="fa fa-file-image-o" aria-hidden="true"></i>
                <%= order.panel.panel_type.total_area %></p>
              </div>
              </div>



                </div>
                </div>
              </div>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="pay-wrap">
          <div class="row">
            <div class="col-md-12">
              <p><strong>Resumo da campanha</strong></p>
            </div>
            <div class="col-md-12 subtotal-text">
              <p><strong>Subtotal ( <%= @campaign.orders.size %> produtos)</strong></p>
              <p><%= humanized_money_with_symbol(@total) %></p>

            </div>
            <div class="col-md-12 subtotal-text">
              <p><strong>Total</strong></p>
              <h6><strong><%= humanized_money_with_symbol(@total) %></strong></h6>

            </div>
            <div class="col-md-12">
              <button class="btn btn-primary btn-pagar" id="pay-button">Pagar</button>
            </div>
        </div>

      </div>

    </div>

  </div>
</div>


<script>
        var button = document.querySelector('#pay-button');
        button.addEventListener('click', function() {
          // inicia a instância do Checkout
          var checkout = new PagarMeCheckout.Checkout({
            encryption_key: 'ek_test_haQ07HnJq4J4TgMhPKUvUymJPksG69',
            success: function(data) {
              console.log(data);
              fetch('<%= payment_url(@campaign) %>', {
                method: 'PATCH',
                credentials: 'include'
              })
              const reload = () => {
                window.location = location
              }
              setInterval(reload, 1000)
            },
            error: function(err) {
              console.log(err);
            },
            close: function() {
              console.log('The modal has been closed.');
            }
          });

          // Obs.: é necessário passar os valores boolean como string
          checkout.open({
            uiColor: '#039EB6',
            amount: <%= @total_cents %>,
            buttonText: 'Pagar',
            buttonClass: 'botao-pagamento btn-primary',
            customerData: 'false',
            createToken: 'true',
            maxInstallments: 6,
            paymentMethods: 'credit_card, boleto',
            customer: {
              external_id: '<%= @campaign.company.id %>',
              name: '<%= @campaign.company.name %>',
              type: 'individual',
              country: 'br',
              email: '<%= current_user.email %>',
              documents: [
                {
                  type: 'cpf',
                  number: '<%= current_user.cpf.gsub(/\D/, '') %>'
                },
                {
                  type: 'cnpj',
                  number: '+<%= @campaign.company.cnpj.gsub(/\D/, '') %>'
                }
              ],
              phone_numbers: ['+<%= j current_user.phone_number.gsub(/\D/, '') %>'],
            },
            defaultInstallment: 1,
            billing: {
              name: '<%= @campaign.company.name %>',
              address: {
                country: 'br',
                state: '<%= @campaign.company.state %>',
                city: '<%= @campaign.company.city %>',
                neighborhood: '<%= @campaign.company.address2 %>',
                street: '<%= @campaign.company.address1 %>',
                street_number: '<%= @campaign.company.street_number %>',
                zipcode: '<%= @campaign.company.zip_code.tr('-', '') %>'
              }
            },
            items: <%= raw @orders.to_json %>
          });
        });
        </script>

app/views/campaigns/_paid.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="title-wrap">
      <h4><%= @campaign.title %> - <%= @campaign.company.name %></h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panels-wrap">
        <ul class="list-unstyled">
        <% @campaign.orders.each do |order| %>
          <li>
            <div class="row">
              <div class="col-sm-12 col-md-3 pic-wrap">
                <%= cl_image_tag(order.panel.panel_type.picture, class:"pic") %></p>
              </div>
              <div class="col-sm-12 col-md-9">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-info">
                        <p><strong><%= order.panel.panel_type.name %></strong></p>
                        <p><%= humanized_money_with_symbol(order.price) %></p>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-12">
                        <div class="row">
                          <div class="col-xs-12 printing-data">
                            <table class="table table-bordered">
                              <thead>
                                <tr>
                                  <th>Area total:</th>
                                  <th>Area visivel:</th>
                                  <th>Area de segurança:</th>
                                  <th>Impressão:</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td><%= order.panel.panel_type.total_area %></td>
                                  <td><%= order.panel.panel_type.visible_area %></td>
                                  <td><%= order.panel.panel_type.security_area %></td>
                                  <td><%= order.panel.panel_type.impression %></td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>

                        <div class="row">
                          <div class="col-md-12">
                            <div class="order-infos">
                              <p><i class="fa fa-train" aria-hidden="true"></i> <%= order.panel.station.name %></p>
                              <p><i class="fa fa-calendar-o" aria-hidden="true"></i> <%= order.date.to_date.strftime("%d/%m/%Y") %></p>
                              <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= order.duration %> dias</p>
                              <p><i class="fa fa-file-image-o" aria-hidden="true"></i>
                              <%= order.panel.panel_type.total_area %></p>
                            </div>
                          </div>
                        </div>

                        <div class="row">
                          <div class="col-md-12">
                            <div class="order-status">
                              <% if order.art.url.nil? %>
                                <%= simple_form_for(order, html: { id: 'art-upload', class: 'dropzone ' + dom_id(order)}) do |f| %>
                                <% end %>
                                <p id="pendent" class="<%= dom_id(order) %>"><i class="fa fa-clock-o" aria-hidden="true"></i> Arte pendente</p>
                              <% else %>
                                <%= cl_image_tag order.art, width: 230, class: 'dropzone-art #{dom_id(order)}' %>
                                <p id="art-status" class="text-center <%= dom_id(order) %>"><i class="fa fa-check-circle" aria-hidden="true"></i> Arte aprovada</p>
                              <% end %>
                            </div>
                          </div>
                        </div>

                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </li>
        <% end %>
        </ul>
      </div>
    </div>

  </div>
  <div class="row">
    <div class="col-md-12">
      <p class="obs-footer">A arte deve ser enviada no maximo 15 dias antes do início da veículação. A JCDecaux se responsabiliza pela aprovação do visual e a impressão do cartaz.</p>
    </div>
  </div>

</div>

app/views/campaigns/destroy.js.erb
var campaign = document.querySelector("[data-campaign-id='<%= @campaign.id %>']")
  if (campaign.parentElement.parentElement.childElementCount === 1) {
    campaign.parentElement.parentElement.parentElement.insertAdjacentHTML("afterbegin", "<em><h5>Você ainda não possui empresas registradas</h5></em>")
  }
  campaign.parentElement.remove()

app/views/campaigns/edit.html.erb
<%= render "campaigns/form" %>

app/views/campaigns/new.html.erb
<h1>teste</h1>
<%= simple_form_for [@company, @campaign] do |f| %>
  <%= f.input :title %>
  <%= f.submit %>
<% end %>

app/views/campaigns/show.html.erb
<% if @campaign.paid %>
  <%= render 'campaigns/paid' %>
<% else %>
  <%= render 'campaigns/not_paid' %>
<% end %>